# Generated by Django 5.2.2 on 2025-06-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='management',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
